$schema: https://azuremlschemas.azureedge.net/latest/data.schema.json
name: train-fd004
version: 1
type: uri_file
path: azureml://datastores/workspaceblobstore/paths/raw/cmapss/fd004/train/train_FD004.txt
description: NASA C-MAPSS FD004 train file